# Generated by Django 5.1 on 2024-09-02 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=30)),
                ('term', models.CharField(choices=[('Term1', 'Term1'), ('Term2', 'Term2'), ('Term3', 'Term3')], max_length=5)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Intermediary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intermediaryName', models.CharField(max_length=100)),
                ('intermediaryEmail', models.EmailField(max_length=100, unique=True)),
                ('intermediaryPhone', models.CharField(max_length=10, unique=True)),
                ('contactPerson', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Kitale', 'Kitale'), ('Eldoret', 'Eldoret'), ('Nakuru', 'Nakuru'), ('Kajiado', 'Kajiado'), ('Laikipia', 'Laikipia')], max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Tertiary', 'Tertiary')], max_length=10)),
                ('location', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Kitale', 'Kitale'), ('Eldoret', 'Eldoret'), ('Nakuru', 'Nakuru'), ('Kajiado', 'Kajiado'), ('Laikipia', 'Laikipia')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Single-Orphan', 'Single-Orphan'), ('Double-Orphan', 'Double-Orphan'), ('Disadvantaged', 'Disadvantaged')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Continuing', 'Continuing'), ('Graduate', 'Graduate'), ('Undergraduate', 'Undergraduate'), ('Completed', 'Completed'), ('Discontinued', 'Discontinued')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorName', models.CharField(max_length=100)),
                ('donorEmail', models.EmailField(max_length=100, unique=True)),
                ('donorPhone', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=100)),
                ('employeeEmail', models.EmailField(max_length=100, unique=True)),
                ('employeePhone', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('department', models.CharField(choices=[('Research', 'Research'), ('Finance', 'Finance'), ('HR', 'HR'), ('IT', 'IT'), ('Data-entry', 'Data-entry')], max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dateofbirth', models.DateField()),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('class_level', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.CharField(blank=True, choices=[('PrimaryOnly', 'PrimaryOnly'), ('Primary&Secondary', 'Primary&Secondary'), ('Primary&Secondary&Tertiary', 'Primary&Secondary&Tertiary'), ('Secondary&tertiary', 'Secondary&tertiary'), ('TertiaryOnly', 'TertiaryOnly'), ('SecondaryOnly', 'SecondaryOnly'), ('Primary&Tertiary', 'Primary&Tertiary')], max_length=100, null=True)),
                ('backgroundInfo', models.TextField(blank=True, null=True)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotusApp.donor')),
                ('intermediary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotusApp.intermediary')),
                ('primary_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_students', to='lotusApp.school')),
                ('secondary_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_students', to='lotusApp.school')),
                ('tertiary_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tertiary_students', to='lotusApp.school')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lotusApp.studentposition')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotusApp.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotusApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2023', '2023'), ('2024', '2024')], max_length=4)),
                ('bursaries', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotusApp.student')),
            ],
        ),
    ]
