# Generated by Django 5.1 on 2024-08-24 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=100)),
                ('employeeEmail', models.EmailField(max_length=100, unique=True)),
                ('employeePhone', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('department', models.CharField(choices=[('Research', 'Research'), ('Finance', 'Finance'), ('HR', 'HR'), ('IT', 'IT'), ('Data-entry', 'Data-entry')], max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intermediary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intermediaryName', models.CharField(max_length=100)),
                ('intermediaryEmail', models.EmailField(max_length=100, unique=True)),
                ('intermediaryPhone', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Kitale', 'Kitale'), ('Eldoret', 'Eldoret'), ('Nakuru', 'Nakuru'), ('Kajiado', 'Kajiado'), ('Laikipia', 'Laikipia')], max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Kitale', 'Kitale'), ('Eldoret', 'Eldoret'), ('Nakuru', 'Nakuru'), ('Kajiado', 'Kajiado'), ('Laikipia', 'Laikipia')], max_length=10)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('schoolEmail', models.EmailField(max_length=100, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorName', models.CharField(max_length=100)),
                ('donorEmail', models.EmailField(max_length=100, unique=True)),
                ('donorPhone', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('backgroundInfo', models.TextField()),
                ('profilePic', models.FileField(blank=True, upload_to='profile_pics')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotusApp.donor')),
                ('intermediary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotusApp.intermediary')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotusApp.school')),
            ],
        ),
    ]
