# Generated by Django 5.1 on 2024-09-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AlterField(
            model_name='student',
            name='position',
            field=models.CharField(blank=True, choices=[('Continuing', 'Continuing'), ('Graduate', 'Graduate'), ('Undergraduate', 'Undergraduate'), ('Completed', 'Completed'), ('Discontinued', 'Discontinued')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('Single-Orphan', 'Single-Orphan'), ('Double-Orphan', 'Double-Orphan'), ('Disadvantaged', 'Disadvantaged'), ('Disabled', 'Disabled')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='StudentPosition',
        ),
    ]
