# Generated by Django 5.1 on 2024-08-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
