# Generated by Django 5.1 on 2024-09-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0002_delete_status_alter_student_position_student_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='schoolEmail',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
