# Generated by Django 5.1 on 2024-09-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0003_school_phone_school_schoolemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
    ]
