# Generated by Django 5.1 on 2024-09-03 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0004_remove_student_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='intermediary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermediary', to='lotusApp.intermediary'),
        ),
    ]
