# Generated by Django 5.1 on 2024-08-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0004_alter_donor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='backgroundInfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
