# Generated by Django 5.1 on 2024-09-03 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0005_alter_student_donor_alter_student_intermediary'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('Donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotusApp.donor')),
            ],
        ),
    ]
