# Generated by Django 5.1 on 2024-08-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0006_alter_student_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Level',
            field=models.CharField(blank=True, choices=[('PrimaryOnly', 'PrimaryOnly'), ('Primary&Secondary', 'Primary&Secondary'), ('Primary&Secondary&Tertiary', 'Primary&Secondary&Tertiary'), ('Secondary&tertiary', 'Secondary&tertiary'), ('TertiaryOnly', 'TertiaryOnly'), ('SecondaryOnly', 'SecondaryOnly'), ('Primany&Tertiary', 'Primany&Tertiary')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
