# Generated by Django 5.1 on 2024-09-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0006_feecommitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecommitment',
            name='year',
            field=models.CharField(blank=True, choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='feecommitment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
