# Generated by Django 5.1 on 2024-08-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0008_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Level',
            new_name='level',
        ),
    ]
