# Generated by Django 5.1 on 2024-09-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0009_alter_feecommitment_donor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeeCommitment',
        ),
    ]
