# Generated by Django 5.1 on 2024-08-30 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0010_alter_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='position',
            field=models.CharField(blank=True, default='Continuing', max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='StudentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Continuing', 'Continuing'), ('Graduate', 'Graduate'), ('Undergraduate', 'Undergraduate'), ('Completed', 'Completed'), ('Discontinued', 'Discontinued')], max_length=25)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lotusApp.student')),
            ],
        ),
    ]
