# Generated by Django 5.1 on 2024-09-05 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0010_delete_feecommitment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('committed_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('contributed_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_amounts', to='lotusApp.donor')),
            ],
            options={
                'unique_together': {('donor', 'year')},
            },
        ),
    ]
