# Generated by Django 5.1 on 2024-08-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0011_student_position_studentposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediary',
            name='contactPerson',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
