# Generated by Django 5.1 on 2024-09-05 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0011_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='committed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='fees',
            name='contributed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='fees',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees_amounts', to='lotusApp.donor'),
        ),
        migrations.AlterField(
            model_name='fees',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
