# Generated by Django 5.1 on 2024-09-05 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0012_alter_fees_committed_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fees',
        ),
    ]
