# Generated by Django 5.1 on 2024-09-01 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0012_intermediary_contactperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=30)),
                ('term', models.CharField(choices=[('Term1', 'Term1'), ('Term2', 'Term2'), ('Term3', 'Term3')], max_length=5)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Tertiary', 'Tertiary')], max_length=10)),
                ('location', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Mombasa', 'Mombasa'), ('Kisumu', 'Kisumu'), ('Kitale', 'Kitale'), ('Eldoret', 'Eldoret'), ('Nakuru', 'Nakuru'), ('Kajiado', 'Kajiado'), ('Laikipia', 'Laikipia')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Single-Orphan', 'Single-Orphan'), ('Double-Orphan', 'Double-Orphan'), ('Disadvantaged', 'Disadvantaged')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentposition',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='studentposition',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='class_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='position',
            field=models.ForeignKey(default='Continuing', on_delete=django.db.models.deletion.CASCADE, to='lotusApp.studentposition'),
        ),
        migrations.CreateModel(
            name='AcademicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2023', '2023'), ('2024', '2024')], max_length=4)),
                ('bursaries', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotusApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotusApp.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotusApp.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='primary_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_students', to='lotusApp.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='secondary_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_students', to='lotusApp.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='tertiary_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tertiary_students', to='lotusApp.school'),
        ),
    ]
