# Generated by Django 5.1 on 2024-09-01 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0013_exam_school_status_remove_studentposition_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotusApp.studentposition'),
        ),
    ]
