# Generated by Django 5.1 on 2024-09-05 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0013_delete_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('committed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('contributed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees_amounts', to='lotusApp.donor')),
            ],
            options={
                'unique_together': {('donor', 'year')},
            },
        ),
    ]
