# Generated by Django 5.1 on 2024-09-05 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0015_alter_fees_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees_amounts', to='lotusApp.donor'),
        ),
    ]
