# Generated by Django 5.1 on 2024-09-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0017_alter_fees_committed_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdonorhistory',
            name='changed_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
