# Generated by Django 5.1 on 2024-09-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0019_academicprogress_school_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicProgress',
        ),
    ]
