# Generated by Django 5.1 on 2024-09-15 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0020_delete_academicprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('school_level', models.CharField(blank=True, max_length=25, null=True)),
                ('bursaries', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotusApp.student')),
            ],
        ),
    ]
