# Generated by Django 5.1 on 2024-09-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotusApp', '0021_academicprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdonorhistory',
            name='school_level',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='studentdonorhistory',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
